---
name: people
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - setuptools
  - pip:
      - tensorflow==2.2.2
      - argparse==1.4.0
      - matplotlib==3.5.1
      - opencv-python==4.1.2.30
      - scipy==1.8.0
      - tqdm==4.64.0
